import type { ProviderDescriptor } from "@/types";

const keyField = {
  key: "apiKey",
  label: "API Key",
  type: "password" as const,
  required: true,
  placeholder: "sk-…",
  group: "认证",
};

const nameField = {
  key: "name",
  label: "Credential Name",
  type: "text" as const,
  required: true,
  placeholder: "Production / Backup",
  group: "基础",
};

export const PROVIDER_DESCRIPTORS: ProviderDescriptor[] = [
  {
    id: "openai",
    name: "OpenAI",
    family: "OpenAI",
    color: "#10a37f",
    mark: "OA",
    builtin: true,
    authSchemes: ["api_key", "project"],
    endpoints: ["chat", "responses", "embeddings", "images", "audio"],
    capabilities: ["chat", "responses", "tools", "vision", "image", "embedding", "audio", "coding", "reasoning", "streaming", "json"],
    formFields: [
      nameField,
      keyField,
      { key: "organizationId", label: "Organization ID", type: "text", placeholder: "org-…", group: "项目" },
      { key: "projectId", label: "Project ID", type: "text", placeholder: "proj_…", group: "项目" },
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.openai.com/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://api.openai.com/v1",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    family: "Google",
    color: "#4285f4",
    mark: "G",
    builtin: true,
    authSchemes: ["api_key", "oauth", "project"],
    endpoints: ["chat", "responses", "embeddings", "images", "audio"],
    capabilities: ["chat", "responses", "tools", "vision", "image", "embedding", "audio", "coding", "reasoning", "streaming", "json"],
    regions: ["us-central1", "europe-west1", "asia-northeast1"],
    formFields: [
      nameField,
      keyField,
      { key: "projectId", label: "Google Project", type: "text", placeholder: "my-gcp-project", group: "项目" },
      {
        key: "region",
        label: "Region",
        type: "select",
        group: "连接",
        options: [
          { value: "us-central1", label: "us-central1" },
          { value: "europe-west1", label: "europe-west1" },
          { value: "asia-northeast1", label: "asia-northeast1" },
        ],
      },
    ],
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
  },
  {
    id: "cliproxy",
    name: "CLI OAuth Bridge",
    family: "CLIProxy",
    color: "#22d3ee",
    mark: "CP",
    builtin: true,
    authSchemes: ["oauth", "api_key"],
    endpoints: ["chat", "responses"],
    capabilities: ["chat", "responses", "tools", "vision", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "CLIProxy Base URL", type: "url", required: true, placeholder: "http://127.0.0.1:8317", group: "连接" },
      { key: "apiKey", label: "CLIProxy 消费 Key（可选）", type: "password", placeholder: "桥接要求时填写", group: "认证" },
      { key: "managementKey", label: "Management Key（可选）", type: "password", placeholder: "remote-management secret", group: "认证" },
    ],
    defaultBaseUrl: "http://127.0.0.1:8317",
    docsHint: "把 EasyCLIProxyAPI / CLIProxyAPI 当作官方 OAuth 资源池。先在桥接里完成 Gemini CLI / Claude Code / Codex / Antigravity 登录，再在此同步模型。",
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI OAuth",
    family: "Google",
    color: "#4285f4",
    mark: "GC",
    builtin: true,
    authSchemes: ["oauth"],
    endpoints: ["chat", "responses"],
    capabilities: ["chat", "responses", "tools", "vision", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "CLIProxy URL", type: "url", required: true, placeholder: "http://127.0.0.1:8317", group: "连接" },
      { key: "managementKey", label: "Management Key（可选）", type: "password", group: "认证" },
    ],
    defaultBaseUrl: "http://127.0.0.1:8317",
    docsHint: "仅使用 Google 官方 OAuth。不要粘贴网页 Cookie。",
  },
  {
    id: "claude-code",
    name: "Claude Code OAuth",
    family: "Anthropic",
    color: "#d97757",
    mark: "CC",
    builtin: true,
    authSchemes: ["oauth"],
    endpoints: ["chat", "responses"],
    capabilities: ["chat", "responses", "tools", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "CLIProxy URL", type: "url", required: true, placeholder: "http://127.0.0.1:8317", group: "连接" },
      { key: "managementKey", label: "Management Key（可选）", type: "password", group: "认证" },
    ],
    defaultBaseUrl: "http://127.0.0.1:8317",
    docsHint: "仅使用 Anthropic 官方 Claude Code OAuth。",
  },
  {
    id: "openai-codex",
    name: "OpenAI Codex OAuth",
    family: "OpenAI",
    color: "#10a37f",
    mark: "CX",
    builtin: true,
    authSchemes: ["oauth"],
    endpoints: ["chat", "responses"],
    capabilities: ["chat", "responses", "tools", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "CLIProxy URL", type: "url", required: true, placeholder: "http://127.0.0.1:8317", group: "连接" },
      { key: "managementKey", label: "Management Key（可选）", type: "password", group: "认证" },
    ],
    defaultBaseUrl: "http://127.0.0.1:8317",
    docsHint: "仅使用 OpenAI 官方 Codex / ChatGPT 订阅 OAuth。",
  },
  {
    id: "antigravity",
    name: "Google Antigravity",
    family: "Google",
    color: "#8ab4f8",
    mark: "AG",
    builtin: true,
    authSchemes: ["oauth"],
    endpoints: ["chat", "responses", "agent"],
    capabilities: ["chat", "responses", "tools", "vision", "coding", "agent", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "CLIProxy URL", type: "url", required: true, placeholder: "http://127.0.0.1:8317", group: "连接" },
      { key: "managementKey", label: "Management Key（可选）", type: "password", group: "认证" },
    ],
    defaultBaseUrl: "http://127.0.0.1:8317",
    docsHint: "仅使用 Google 官方 Antigravity OAuth。不要粘贴网页 Cookie / Session。",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    family: "Anthropic",
    color: "#d97757",
    mark: "AN",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "responses"],
    capabilities: ["chat", "responses", "tools", "vision", "coding", "reasoning", "streaming", "json"],
    formFields: [
      nameField,
      { ...keyField, placeholder: "sk-ant-…" },
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.anthropic.com", group: "连接" },
    ],
    defaultBaseUrl: "https://api.anthropic.com",
  },
  {
    id: "glm",
    name: "GLM",
    family: "Zhipu",
    color: "#165dff",
    mark: "智",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "vision", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://open.bigmodel.cn/api/paas/v4", group: "连接" },
    ],
    defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
  },
  {
    id: "kimi",
    name: "Kimi",
    family: "Moonshot",
    color: "#f5c518",
    mark: "K",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat"],
    capabilities: ["chat", "tools", "vision", "coding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.moonshot.cn/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://api.moonshot.cn/v1",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    family: "DeepSeek",
    color: "#4d6bfe",
    mark: "DS",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat"],
    capabilities: ["chat", "tools", "coding", "reasoning", "streaming", "json"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.deepseek.com", group: "连接" },
    ],
    defaultBaseUrl: "https://api.deepseek.com",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    family: "OpenRouter",
    color: "#6566f1",
    mark: "OR",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "vision", "embedding", "coding", "reasoning", "streaming"],
    formFields: [
      nameField,
      { ...keyField, placeholder: "sk-or-…" },
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://openrouter.ai/api/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://openrouter.ai/api/v1",
  },
  {
    id: "volcengine",
    name: "火山方舟",
    family: "ByteDance",
    color: "#1664ff",
    mark: "火",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "vision", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "endpointId", label: "Endpoint ID", type: "text", placeholder: "ep-…", group: "项目" },
      { key: "region", label: "Region", type: "text", placeholder: "cn-beijing", group: "连接" },
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://ark.cn-beijing.volces.com/api/v3", group: "连接" },
    ],
    defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
  },
  {
    id: "bailian",
    name: "阿里云百炼",
    family: "Alibaba",
    color: "#ff6a00",
    mark: "阿",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "vision", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://dashscope.aliyuncs.com/compatible-mode/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
  },
  {
    id: "hunyuan",
    name: "腾讯混元",
    family: "Tencent",
    color: "#00a4ff",
    mark: "混",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "vision", "embedding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.hunyuan.cloud.tencent.com/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    family: "SiliconFlow",
    color: "#7c5cfc",
    mark: "SF",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings", "rerank"],
    capabilities: ["chat", "tools", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.siliconflow.cn/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://api.siliconflow.cn/v1",
  },
  {
    id: "groq",
    name: "Groq",
    family: "Groq",
    color: "#f55036",
    mark: "GQ",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "audio"],
    capabilities: ["chat", "tools", "audio", "streaming"],
    formFields: [
      nameField,
      { ...keyField, placeholder: "gsk_…" },
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.groq.com/openai/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://api.groq.com/openai/v1",
  },
  {
    id: "together",
    name: "Together AI",
    family: "Together",
    color: "#0f6fff",
    mark: "TG",
    builtin: true,
    authSchemes: ["api_key"],
    endpoints: ["chat", "embeddings", "images"],
    capabilities: ["chat", "tools", "image", "embedding", "streaming"],
    formFields: [
      nameField,
      keyField,
      { key: "baseUrl", label: "Base URL", type: "url", placeholder: "https://api.together.xyz/v1", group: "连接" },
    ],
    defaultBaseUrl: "https://api.together.xyz/v1",
  },
  {
    id: "ollama",
    name: "Ollama",
    family: "Local",
    color: "#c2c2c2",
    mark: "OL",
    local: true,
    builtin: true,
    authSchemes: ["local"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "vision", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "Base URL", type: "url", required: true, placeholder: "http://localhost:11434", group: "连接" },
    ],
    defaultBaseUrl: "http://localhost:11434",
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    family: "Local",
    color: "#6ee7b7",
    mark: "LM",
    local: true,
    builtin: true,
    authSchemes: ["local"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "Base URL", type: "url", required: true, placeholder: "http://localhost:1234/v1", group: "连接" },
    ],
    defaultBaseUrl: "http://localhost:1234/v1",
  },
  {
    id: "vllm",
    name: "vLLM",
    family: "Local",
    color: "#22d3ee",
    mark: "VL",
    local: true,
    builtin: true,
    authSchemes: ["api_key", "local"],
    endpoints: ["chat", "embeddings"],
    capabilities: ["chat", "tools", "embedding", "coding", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "Base URL", type: "url", required: true, placeholder: "http://localhost:8001/v1", group: "连接" },
      { key: "apiKey", label: "API Key", type: "password", placeholder: "optional", group: "认证" },
    ],
    defaultBaseUrl: "http://localhost:8001/v1",
  },
  {
    id: "localai",
    name: "LocalAI",
    family: "Local",
    color: "#a78bfa",
    mark: "LA",
    local: true,
    builtin: true,
    authSchemes: ["local", "api_key"],
    endpoints: ["chat", "embeddings", "images", "audio"],
    capabilities: ["chat", "embedding", "image", "audio", "streaming"],
    formFields: [
      nameField,
      { key: "baseUrl", label: "Base URL", type: "url", required: true, placeholder: "http://localhost:8080/v1", group: "连接" },
    ],
    defaultBaseUrl: "http://localhost:8080/v1",
  },
  {
    id: "custom-openai",
    name: "Custom OpenAI Compatible",
    family: "Custom",
    color: "#94a3b8",
    mark: "CU",
    builtin: false,
    authSchemes: ["api_key", "bearer", "custom_header"],
    endpoints: ["chat", "responses", "embeddings"],
    capabilities: ["chat", "responses", "tools", "streaming", "json"],
    formFields: [
      nameField,
      { key: "providerName", label: "Provider Name", type: "text", required: true, placeholder: "My Upstream", group: "基础" },
      { key: "baseUrl", label: "Base URL", type: "url", required: true, placeholder: "https://api.example.com/v1", group: "连接" },
      keyField,
      { key: "chatEndpoint", label: "Chat Endpoint", type: "text", placeholder: "/chat/completions", group: "端点" },
      { key: "responsesEndpoint", label: "Responses Endpoint", type: "text", placeholder: "/responses", group: "端点" },
      { key: "modelsEndpoint", label: "Models Endpoint", type: "text", placeholder: "/models", group: "端点" },
      { key: "headers", label: "Custom Headers", type: "headers", group: "连接", help: "Authorization / X-API-Key / User-Agent" },
      { key: "timeoutMs", label: "Timeout (ms)", type: "number", placeholder: "60000", group: "策略" },
      { key: "retry", label: "Retry", type: "number", placeholder: "2", group: "策略" },
      { key: "modelMapping", label: "Model Mapping", type: "textarea", placeholder: "coding -> gpt-custom", group: "策略" },
    ],
  },
];

export function getDescriptor(id: string) {
  return PROVIDER_DESCRIPTORS.find((d) => d.id === id);
}

export const AUTH_SCHEME_LABEL: Record<string, string> = {
  api_key: "API Key",
  bearer: "Bearer Token",
  oauth: "OAuth",
  service_account: "Service Account",
  project: "Project Credential",
  env: "Environment Variable",
  local: "Local Connection",
  custom_header: "Custom Header",
};
